### ISSUE TITLE
Running AcademicPaperClassifierTest, dataset_reader's type not found.

### ISSUE THREAD

**Issue by zhangzexdu** [allenai/allennlp-as-a-library-example#28]
python3 academic_paper_classifier_test.py
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
2019-03-11 21:14:11,580 - INFO - allennlp.common.checks - Pytorch version: 1.0.1.post2

2019-03-11 21:14:11,610 - INFO - allennlp.common.from_params - instantiating class <class 'allennlp.data.dataset_readers.dataset_reader.DatasetReader'> from params {'type': 's2_papers'} and extras {}
E
======================================================================
ERROR: test_model_can_train_save_and_load (__main__.AcademicPaperClassifierTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "academic_paper_classifier_test.py", line 12, in setUp
    self.set_up_model('/home/kindler/Projects/2019/M03/re_all/dataset/allennlp_test/allennlp-as-a-library-example/tests/fixtures/academic_paper_classifier.json', '/home/kindler/Projects/2019/M03/re_all/dataset/allennlp_test/allennlp-as-a-library-example/tests/fixtures/s2_papers.jsonl'),
  File "/home/kindler/.local/lib/python3.6/site-packages/allennlp/common/testing/model_test_case.py", line 25, in set_up_model
    reader = DatasetReader.from_params(params['dataset_reader'])
  File "/home/kindler/.local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 275, in from_params
    default_to_first_choice=default_to_first_choice)
  File "/home/kindler/.local/lib/python3.6/site-packages/allennlp/common/params.py", line 317, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: "s2_papers not in acceptable choices for dataset_reader.type: ['ccgbank', 'conll2003', 'conll2000', 'ontonotes_ner', 'coref', 'winobias', 'event2mind', 'interleaving', 'language_modeling', 'multiprocess', 'ptb_trees', 'squad', 'quac', 'triviaqa', 'qangaroo', 'srl', 'semantic_dependencies', 'seq2seq', 'sequence_tagging', 'snli', 'universal_dependencies', 'sst_tokens', 'quora_paraphrase', 'atis', 'nlvr', 'wikitables', 'template_text2sql', 'grammar_based_text2sql', 'quarel', 'simple_language_modeling', 'babi', 'copynet_seq2seq', 'text_classification_json']"

**Comment by matt-gardner** [comment]
You need to be sure that the models get imported, so that they get registered in allennlp.  That happens here: https://github.com/allenai/allennlp-as-a-library-example/blob/2b2ff0ac8d66ad4cb1c434998aeb667e324af0f6/my_library/__init__.py#L1-L4

So, because you're running this directly from that one file, instead of using pytest or something from the top-level directory, those lines aren't getting run, and the model isn't getting registered.

**Comment by zhangzexdu** [comment]
Thanks，I have solved the problems as your guides.
