### ISSUE TITLE
key "type" required at location "model.text_field_embedder."

### ISSUE THREAD

**Issue by NoviScl** [allenai/allennlp-as-a-library-example#30]
I am using allennlp 0.8.4 and following this example. It gives the error: allennlp.common.checks.ConfigurationError: 'key "type" is required at location "model.text_field_embedder."'

Any idea how to fix it?

**Comment by matt-gardner** [comment]
Can you give a complete stack trace, please?

**Comment by NoviScl** [comment]
Sure:

Traceback (most recent call last):
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/common/params.py", line 246, in pop
    value = self.params.pop(key)
KeyError: 'type'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/run.py", line 21, in <module>
    run()
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/commands/train.py", line 116, in train_model_from_args
    args.cache_prefix)
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/commands/train.py", line 160, in train_model_from_file
    cache_directory, cache_prefix)
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/commands/train.py", line 218, in train_model
    cache_prefix)
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/training/trainer.py", line 793, in from_params
    model = Model.from_params(vocab=vocab, params=params.pop('model'))
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/common/from_params.py", line 386, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/common/from_params.py", line 133, in create_kwargs
    kwargs[name] = construct_arg(cls, name, annotation, param.default, params, **extras)
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/common/from_params.py", line 229, in construct_arg
    return annotation.from_params(params=subparams, **subextras)
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/common/from_params.py", line 359, in from_params
    default_to_first_choice=default_to_first_choice)
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/common/params.py", line 331, in pop_choice
    value = self.pop(key, default)
  File "/Users/sichenglei/Desktop/kaggle/salt/venv/lib/python3.6/site-packages/allennlp/common/params.py", line 248, in pop
    raise ConfigurationError("key \"{}\" is required at location \"{}\"".format(key, self.history))
allennlp.common.checks.ConfigurationError: 'key "type" is required at location "model.text_field_embedder."'

**Comment by matt-gardner** [comment]
Ok, looks like we also need the config file that you're using.

**Comment by NoviScl** [comment]
I am using the exact same config file here: https://github.com/allenai/allennlp-as-a-library-example/blob/master/experiments/venue_classifier.json

Only difference is that I have put the dataset_reader, model and predictor in the same directory (with a __init__.py) instead of putting them each in a new subdirectory inside 'my_library'.

**Comment by matt-gardner** [comment]
I just did a fresh clone of this repo and ran this experiment using the latest allennlp master.  I am not able to reproduce this bug.  Maybe I could help more if you gave the logging output also?  I'm really not sure why you would be seeing this.

**Comment by NoviScl** [comment]
Hi Matt, after checking again I realise that it is my own problem. I was playing with different model and configurations and missed one line in the configuration file. Just cloned the whole repo again and it indeed works fine. Sorry for all the confusions!
